# steps:
#   # Step 1: Build the image using Google Buildpacks (no Dockerfile)
#   - name: 'gcr.io/buildpacks/builder:v1'
#     args:
#       [
#         'build',
#         'gcr.io/$PROJECT_ID/odoo',
#         '--env', 'GOOGLE_RUNTIME=python',
#         '--env', 'GOOGLE_ENTRYPOINT=chmod u+x start_server_heroku.sh && ./start_server_heroku.sh'
#       ]

# images:
#   - 'gcr.io/$PROJECT_ID/odoo'
# options:
#   logging: CLOUD_LOGGING_ONLY

steps:
  # 1. Use a standard Python builder
  - name: 'python:3.10'
    entrypoint: 'bash'
    args:
      chmod u+x start_server_heroku.sh
      ./start_server_heroku.sh

        
        

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1800s


# python odoo-bin \
#           -c odoo.conf \
#           -d ${ODOO_DB_NAME} \
#           -u ${ODOO_UPDATE_MODULES} \
#           --stop-after-init