[options]
db_host = ifsm9d.stackhero-network.com
db_port = 6248
db_user = admin
db_password = NN2ERwlsBgeBXaXni4GwStjbwxRbaEP5
database = link2launch

addons_path = addons,
    custom_addons/web,
    custom_addons/fs_storage,
    custom_addons/server-env,
    custom_addons/connector

;----------------------------------
; AWS S3 attachment storage
;----------------------------------
[fs_storage]
ir_attachment.location = s3
s3.bucket = l2l-odoo-db-filestore
s3.location = qng43y.stackhero-network.com
s3.region = us-east-1
s3.key = GuVRC11cbW6w1M8JYD5P
s3.secret = 1AnAHogRdHPmMIxMBae6TmposyjJkqN3uX6Q9Nek

# {
#     "key":"GuVRC11cbW6w1M8JYD5P",
#     "secret":"1AnAHogRdHPmMIxMBae6TmposyjJkqN3uX6Q9Nek",
#     "endpoint_url":"qng43y.stackhero-network.com",
#     "kwargs":{
#       "region_name": "us-east-1"
#     }
# }


# host: str
#     The remote server name/ip to connect to
# port: int
#     Port to connect with
# username: str or None
#     If authenticating, the user's identifier
# password: str of None
#     User's password on the server, if using
# acct: str or None
#     Some servers also need an "account" string for auth
# block_size: int or None
#     If given, the read-ahead or write buffer size.
# tempdir: str
#     Directory on remote to put temporary files when in a transaction
# timeout: int
#     Timeout of the ftp connection in seconds
# encoding: str
#     Encoding to use for directories and filenames in FTP connection
# tls: bool
#     Use FTP-TLS, by default False

# {
#     "host":"sparkling-water-50295.sftptogo.com",
#     "username":"0b37c5c179bb36a71a67cc909e56e0",
#     "password":"AkgILLNS8RlWtce79etxBJNMhdRO93",
#     "tempdir":"tmp"
# }