[options]
db_host = ifsm9d.stackhero-network.com
db_port = 6248
db_user = admin
db_password = NN2ERwlsBgeBXaXni4GwStjbwxRbaEP5
database = link2launch

addons_path = addons,custom_addons/web
# ,custom_addons/storage,custom_addons/server-env

;----------------------------------
; AWS S3 attachment storage
;----------------------------------
[fs_storage]
ir_attachment.location = s3
s3.bucket = l2l-odoo-db-filestore
s3.location = qng43y.stackhero-network.com
s3.region = us-east-1
s3.key = GuVRC11cbW6w1M8JYD5P
s3.secret = 1AnAHogRdHPmMIxMBae6TmposyjJkqN3uX6Q9Nek
