[options]
db_host = ${DATABASE_URL}
db_port = 6248
db_user = ${DB_USER}
db_password = ${DB_PASSWORD}
database = ${DB_NAME}

;----------------------------------
; AWS S3 attachment storage
;----------------------------------
ir_attachment.location = s3
s3.bucket = ${S3_BUCKET}
s3.location = s3.amazonaws.com
s3.region = ${S3_REGION}
; optional: if not using IAM roles
s3.key = ${AWS_ACCESS_KEY_ID}
s3.secret = ${AWS_SECRET_ACCESS_KEY}

addons_path = custom_addons/web,addons,custom_addons/storage,custom_addons/server-env
